export const CREATE_SLIDE = 'CREATE_SLIDE';
export const DELETE_SLIDE = 'DELETE_SLIDE';
export const SAVE_SLIDE = 'SAVE_SLIDE';
export const LOAD_PRESENTATION = 'LOAD_PRESENTATION';
export const SAVE_PRESENTATION = 'SAVE_PRESENTATION';